### PR TITLE
#18 Use GCHandle to keep delegate in memory for callbacks

### PR DESCRIPTION
**Pull request by HakanL**
Solves the issue with disposing of callbacks.

### CODE REVIEW

**Comment by HakanL** [comment]
ok I changed it to just hold a reference to the delegate without GCHandle, seems to work just as well.

**Comment by HakanL** [comment]
I wasn't sure if we still have to set the reference to null when we're getting the END callback type, it may not be necessary?

**Comment by martindevans** [comment]
It can't hurt to set the reference to null. I'll check this over and merge it shortly

**Comment by martindevans** [comment]
Ok I merged this in, and made a few changes myself to unify the repeated callback handling code into one place.

**Comment by HakanL** [comment]
Very good, thanks!

**Pull request merged**
