### PR TITLE
Fmod106

### PR DESCRIPTION
**Pull request by HakanL**

### CODE REVIEW

**Comment by martindevans** [comment]
What was your technique for upgrading the wrapper? One complexity of upgrading was that I had manually modified the wrapper to fix some bugs in it - did you port across these changes or just replace the wrapper with the newest version?

**Comment by HakanL** [comment]
I just replaced the files from the FMOD download and then fixed whatever compile issues were reported. It wasn't too bad, just a couple of fields missing the protection level. I sent an email to FMOD and they said they will incorporate my changes in their new release of their C# wrapper as well (and that's why they noticed the binaries...).

**Comment by martindevans** [comment]
I emailed FMOD exactly the same thing for my changes, and they never got back to me Q_Q

Anyway, I'm going to diff the files I had with the vanilla FMOD files, then compare your diff to my diff and make sure you didn't miss anything. This could take a while but hopefully I'll get it done tonight.

**Comment by HakanL** [comment]
Hehe :)

Sounds good, yea obviously I didn't do a thorough test of all the functionality in the API, I made sure it compiled and that the samples (2) ran fine.

**Comment by martindevans** [comment]
Alright, it looks like you ended up making pretty much the same changes as me. It looks like the only changes you missed are the stuff to do with custom file systems, which were broken anyway so I'm not really bothered about that.

I like the StringWrapper, that seems like a much better way to be managing strings.

I'm about to merge this in, then I'm going to investigate unit testing.

**Comment by HakanL** [comment]
I see. Yea I didn't bother with the file system stuff (more than making it compile, there were a few changes in SSS to match the function signatures).

They had changed to this StringWrapper, not me, I just made it match and compile ;)

Cool, thanks!

**Pull request merged**
